/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#904d00',
        'on-primary': '#ffffff',
        'primary-container': '#ff8c00',
        'on-primary-container': '#623200',
        'primary-fixed': '#ffdcc3',
        'primary-fixed-dim': '#ffb77d',
        'on-primary-fixed': '#2f1500',
        'on-primary-fixed-variant': '#6e3900',
        'inverse-primary': '#ffb77d',
        secondary: '#2d6482',
        'on-secondary': '#ffffff',
        'secondary-container': '#a7dbfe',
        'on-secondary-container': '#29617f',
        'secondary-fixed': '#c6e7ff',
        'secondary-fixed-dim': '#99cdf0',
        'on-secondary-fixed': '#001e2d',
        'on-secondary-fixed-variant': '#0a4c69',
        tertiary: '#44664b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#8eb393',
        'on-tertiary-container': '#24462d',
        'tertiary-fixed': '#c5ecca',
        'tertiary-fixed-dim': '#aad0af',
        'on-tertiary-fixed': '#00210c',
        'on-tertiary-fixed-variant': '#2c4e35',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f4faff',
        'on-background': '#0e1d25',
        surface: '#f4faff',
        'on-surface': '#0e1d25',
        'on-surface-variant': '#564334',
        'surface-bright': '#f4faff',
        'surface-dim': '#ccdce7',
        'surface-tint': '#904d00',
        'surface-variant': '#d5e5ef',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#e7f6ff',
        'surface-container': '#e0f0fb',
        'surface-container-high': '#daebf5',
        'surface-container-highest': '#d5e5ef',
        outline: '#897362',
        'outline-variant': '#ddc1ae',
        'inverse-surface': '#23323a',
        'inverse-on-surface': '#e3f3fd',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        base: '8px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        margin: '32px',
      },
      fontFamily: {
        sans: ['Lexend', 'sans-serif'],
        button: ['Lexend'],
        'body-md': ['Lexend'],
        'body-lg': ['Lexend'],
        'headline-xl': ['Lexend'],
        'headline-md': ['Lexend'],
        'headline-lg': ['Lexend'],
        'label-md': ['Lexend'],
      },
      fontSize: {
        button: ['16px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
