/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#dce2f3',
        primary: '#4d5c8d',
        'on-surface': '#151c27',
        'surface-container-low': '#f0f3ff',
        'outline-variant': '#c3c5d8',
        background: '#f9f9ff',
        'surface-bright': '#f9f9ff',
        'surface-container-high': '#e2e8f8',
        'surface-container-lowest': '#ffffff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        outline: '#737687',
        'on-primary': '#ffffff',
        'surface-container': '#e7eefe',
        secondary: '#006a64',
        'on-secondary': '#ffffff',
        'secondary-container': '#97f3ea',
        'on-secondary-container': '#00716a',
        'primary-container': '#6675a8',
        'on-primary-container': '#000318',
        surface: '#f9f9ff',
        'on-surface-variant': '#434655',
        'on-background': '#151c27',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'stack-lg': '32px',
        'section-gap': '48px',
        'stack-md': '16px',
        'stack-sm': '8px',
        'gutter-mobile': '16px',
        unit: '4px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '14px', fontWeight: '500' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
