const v = (n) => `var(--${n})`

module.exports = {
  safelist: [
    { pattern: /^(bg|text|border|ring|fill|stroke)-(background|foreground|card|popover|primary|secondary|muted|accent|destructive|border|input|ring)(-foreground)?$/ },
    { pattern: /^rounded(-(sm|md|lg|xl|4xl|full|none))?$/ },
    { pattern: /^(p|px|py|pt|pb|pl|pr|m|mx|my|mt|mb|ml|mr|gap|gap-x|gap-y)-(0|0\.5|1|1\.5|2|2\.5|3|4|5|6|8|10|12|16)$/ },
    { pattern: /^(text)-(xs|sm|base|lg|xl|2xl|3xl|4xl)$/ },
    { pattern: /^(font)-(normal|medium|semibold|bold)$/ },
    { pattern: /^(flex|grid|block|inline-flex|inline-block|hidden)$/ },
    { pattern: /^(flex)-(row|col|wrap|1|none)$/ },
    { pattern: /^(items|justify)-(start|end|center|between|around|stretch)$/ },
    { pattern: /^(w|h)-(full|auto|screen|fit)$/ },
    { pattern: /^(max-w)-(xs|sm|md|lg|xl|2xl|full)$/ },
    { pattern: /^(shadow)(-(sm|md|lg|xl|none))?$/ },
    { pattern: /^(border)(-(0|2|4))?$/ },
    { pattern: /^(opacity)-(0|50|70|80|90|100)$/ },
    { pattern: /^(truncate|underline|uppercase|text-left|text-center|text-right)$/ },
  ],
  content: [
    './components/ui/button.jsx',
    './components/ui/card.jsx',
    './components/ui/badge.jsx',
    './components/ui/input.jsx',
    './components/ui/chart.jsx',
    './components/WordToken.jsx',
    './components/ProgressRing.jsx',
    './.design-sync/previews/**/*.tsx',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: v('background'),
        foreground: v('foreground'),
        card: { DEFAULT: v('card'), foreground: v('card-foreground') },
        popover: { DEFAULT: v('popover'), foreground: v('popover-foreground') },
        primary: { DEFAULT: v('primary'), foreground: v('primary-foreground') },
        secondary: { DEFAULT: v('secondary'), foreground: v('secondary-foreground') },
        muted: { DEFAULT: v('muted'), foreground: v('muted-foreground') },
        accent: { DEFAULT: v('accent'), foreground: v('accent-foreground') },
        destructive: { DEFAULT: v('destructive'), foreground: v('primary-foreground') },
        border: v('border'),
        input: v('input'),
        ring: v('ring'),
      },
      borderRadius: {
        lg: v('radius'),
        md: `calc(${v('radius')} - 2px)`,
        sm: `calc(${v('radius')} - 4px)`,
        xl: `calc(${v('radius')} + 4px)`,
        '4xl': '2rem',
      },
      aria: { invalid: 'invalid="true"' },
      ringWidth: { 3: '3px' },
      borderWidth: { 3: '3px' },
    },
  },
  plugins: [],
}
